# credits
# https://github.com/itzg/docker-minecraft-server
version: '3.8'
services:
  mc:
    container_name: admate
    image: itzg/minecraft-server:${IMAGE_TAG:-java17}
    volumes:
    #! mount directory, this is your serverdata
    - ./modpacks:/modpacks:ro
    - ./data:/data
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      #! if you downloaded manually
      CF_SERVER_MOD: /modpacks/${MODPACK:-Admate_server_pack_1.18.2_1.1.zip}
      #! direct download from Curseforge
      #CF_SERVER_MOD: https://mediafilez.forgecdn.net/files/4049/187/Admate_server_pack_1.18.2_1.0.zip
    ports: #! Port specified in server-properties
      - "25566:25565"
#    deploy: #! limiting resources if you want to
#        resources:
#            limits:
#              cpus: 2
#              memory: 5G # Recommended atleast 4 Gigs of RAM
volumes:
  modpacks:
  data:
